# Generated by Django 2.1.7 on 2019-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='diy_package',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
