# Generated by Django 2.1.7 on 2019-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_article_diy_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='package_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
