# Generated by Django 2.1.7 on 2019-04-27 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0005_auto_20190415_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='diy_files',
            field=models.FileField(default='kit.jpg', upload_to='kit/%Y/%m/%D'),
        ),
        migrations.AlterField(
            model_name='articleorder',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.Article'),
        ),
        migrations.AlterField(
            model_name='articleorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.Cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
